# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.create.comment:
        class: AppBundle\forms\CommentType
        tags:
            - { name: create.post, alias: commentForm}
  app.create.rate:
          class: AppBundle\forms\RateType
          tags:
              - { name: create.rate, alias: rateForm}
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
