AppBundle\Entity\Produkcja:
    type: entity
    table: produkcja
    id:
        idProdukcji:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_produkcji
            generator:
                strategy: IDENTITY
    fields:
        nazwa:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
